name: Day 3 - Build Tools Setup

on:
  workflow_dispatch:

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Disk Space
        run: |
          echo "=== DUNG LƯỢNG BAN ĐẦU ==="
          df -h /
          echo "=== ĐANG XÓA CÁC GÓI RÁC TRÊN CLOUD ==="
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/powershell
          echo "=== DUNG LƯỢNG SAU KHI DỌN DẸP ==="
          df -h /

      - name: Install Android Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache flex git gnupg gperf liblz4-tool libncurses5-dev libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3
          echo "Đã cài đặt thành công toàn bộ công cụ biên dịch Android!"
