name: Day 4 - Repo Tool & Manifest Init

on:
  workflow_dispatch:

jobs:
  init-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Google Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "Đã cài đặt công cụ repo thành công!"

      - name: Configure Git Credentials
        run: |
          git config --global user.name "hao874148-lang"
          git config --global user.email "lhao874148@gmail.com"

      - name: Test Repo Init LineageOS 21.0
        run: |
          mkdir -p ~/android-source && cd ~/android-source
          ~/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1
          echo "=== KIỂM TRA MÃ NGUỒN KHỞI TẠO ==="
          ls -la .repo
